package me.devsaki.hentoid.json.sources.pawchive

import com.squareup.moshi.JsonClass
import me.devsaki.hentoid.activities.sources.PAW_DOMAIN_FILTER
import me.devsaki.hentoid.database.domains.Chapter
import me.devsaki.hentoid.database.domains.Content
import me.devsaki.hentoid.enums.Site
import me.devsaki.hentoid.enums.StatusContent
import me.devsaki.hentoid.parsers.cleanup
import me.devsaki.hentoid.parsers.urlsToImageFiles
import me.devsaki.hentoid.util.image.isSupportedMedia
import me.devsaki.hentoid.util.parseDatetimeToEpoch
import java.net.URLEncoder
import java.util.concurrent.atomic.AtomicInteger

/**
 * Pawchive posts generated by calling the "posts" API endpoint
 */
@JsonClass(generateAdapter = true)
data class PawPost(
    val id: String,
    val user: String,
    val service: String,
    val title: String,
    val published: String?,
    //val tags: List<String>?,
    val file: PawAttachment?,
    val attachments: List<PawAttachment>
) {
    fun getImageUrls(): List<String> {
        // Try using attachments
        var result = attachments
            .filter { isSupportedMedia(it.path ?: "") }
            .distinct()
            .map {
                val server = "https://file.$PAW_DOMAIN_FILTER"
                val origin = URLEncoder.encode(it.name ?: "Attachment", "UTF-8")
                "$server/data${it.path}?f=$origin"
            }
        // Add file as the sole attached image
        if (result.isEmpty()) {
            file?.path?.let {
                if (isSupportedMedia(it))
                    result = listOf(
                        "https://img.$PAW_DOMAIN_FILTER/thumbnail/data/${it}"
                            .replace("//", "/")
                    )
            }
        }
        return result
    }

    fun toChapter(
        userId: String,
        chapterOrder: Int,
        pageOrder: AtomicInteger
    ): Chapter {
        // One result = one chapter, if it contains at least an usable picture (i.e. not exclusively MEGA links)
        val chapter = Chapter(
            chapterOrder,
            "https://$PAW_DOMAIN_FILTER/${service}/user/${userId}/post/${id}",
            title,
            id
        )
        val imageUrls = getImageUrls()
        if (imageUrls.isNotEmpty()) {
            val imageFiles = urlsToImageFiles(
                imageUrls,
                "",
                pageOrder.get(),
                StatusContent.SAVED,
                imageUrls.count(),
                chapter
            )
            pageOrder.set(imageFiles.maxOf { it.order } + 1)
            chapter.setImageFiles(imageFiles)
        }
        return chapter
    }

    fun update(content: Content, galleryUrl: String, updateImages: Boolean): Content {
        content.site = Site.PAWCHIVE
        content.url = galleryUrl.replace("/api/v1/", "/")
            .replace("/posts-legacy", "/")
        content.title = cleanup(title)
        content.status = StatusContent.SAVED
        content.uploadDate = 0L
        published?.let {
            // e.g. 2024-11-24T17:51:20
            if (it.isNotEmpty())
                content.uploadDate = parseDatetimeToEpoch(it, "yyyy-MM-dd'T'HH:mm:ss")
        }

        // Map thumb server to picture URL
        val imageUrls = getImageUrls()

        // Use file as cover
        file?.let {
            content.coverImageUrl = "https://img.$PAW_DOMAIN_FILTER/thumbnail/data/${it.path}"
        } ?: run {
            content.coverImageUrl = imageUrls[0]
        }
        if (updateImages) {
            val imgs = urlsToImageFiles(
                imageUrls,
                content.downloadRange,
                StatusContent.SAVED,
                Site.PAWCHIVE,
                content.coverImageUrl
            )
            content.setImageFiles(imgs)
            content.qtyPages = imgs.count { it.isReadable }
        }

        return content
    }
}